### ISSUE TITLE
'BVLinearGradient' not found  Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by baixjian** [react-native-linear-gradient/react-native-linear-gradient#654]
Xcode: Version 15.2 (15C500b)
react-native-linear-gradient: 2.5.6

**Comment by baixjian** [comment]
Apple M1 Pro 
macOs 14.2.1 (23C71)

**Comment by baixjian** [comment]
ld: warning: ignoring duplicate libraries: '-lBVLinearGradient', '-lc++'
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/BVLinearGradient' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Base64' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/CodePush' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/DoubleConversion' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/FBReactNativeSpec' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Folly' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/JCore' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/JPush' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/JWT' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-AppTrackingTransparency' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-BluetoothPeripheral' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Calendars' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Camera' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Contacts' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-FaceID' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-LocationAccuracy' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-LocationAlways' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-LocationWhenInUse' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-MediaLibrary' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Microphone' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Motion' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Notifications' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-PhotoLibrary' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-PhotoLibraryAddOnly' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Reminders' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-Siri' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-SpeechRecognition' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Permission-StoreKit' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RCTHttpCache' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RCTTypeSafety' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RCTWeChat' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNBugly' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNCAsyncStorage' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNCClipboard' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNCMaskedView' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNCPicker' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNDeviceInfo' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNExitApp' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNFS' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNFastImage' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNGestureHandler' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNImageCropPicker' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNLocalize' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNPermissions' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNReanimated' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNSVG' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNScreens' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNShare' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RNSyanImagePicker' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-Core' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-CoreModules' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTAnimation' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTBlob' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTImage' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTLinking' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTNetwork' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTSettings' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTText' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-RCTVibration' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-cxxreact' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-jsi' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-jsiexecutor' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/React-jsinspector' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/ReactCommon' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/ReactNativeDarkMode' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/ReactNativeKeyboardManager' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/SDWebImage' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/SDWebImageWebPCoder' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/SSZipArchive' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/TOCropViewController' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/TZImagePickerController' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Yoga' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/glog' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/libwebp' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-amap-geolocation' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-camera' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-cameraroll' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-document-picker' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-fingerprint-scanner' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-image-picker' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-image-resizer' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-orientation-locker' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-pdf' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-progress-view' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-qr-scanner' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-safe-area-context' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-splash-screen' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-viewpager' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/react-native-webview' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/rn-fetch-blob' not found
ld: warning: search path '/Users/liuxiwei/gafc/mobile_app/ios/GPSSdk/vehicleloan' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Alamofire' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/CryptoSwift' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/IQKeyboardManager' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/JXSegmentedView' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/LBXScan' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/MBProgressHUD' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/MJRefresh' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/Moya' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/RxSwift' not found
ld: warning: search path '/Users/liuxiwei/Library/Developer/Xcode/DerivedData/gafc-apljoqarovmpsabpgiysfwiinhxi/Build/Products/Debug-iphoneos/SnapKit' not found
ld: warning: search path '/Users/liuxiwei/gafc/mobile_app/ios/GPSSdk/vehicleLoan' not found
ld: warning: search path '/Users/liuxiwei/gafc/mobile_app/ios/JMProtection' not found
ld: library 'BVLinearGradient' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by matt-tek** [comment]
Hello ! i got exactly the same problem here on macOs with an M2 pro and Xcode 15.2

**Comment by Stafox** [comment]
Faced same issue. My assumption that it is somehow connected to environment (cocoapods, for instance) as I stuck with this issue right after moving project to erased macos (same laptop). Now it fails.

**Comment by baixjian** [comment]
Has anyone solved the problem

**Comment by Stafox** [comment]
So, my issue was connected to incorrect Libraries search path. Check the pathes in xcode's error, and check are there any files/folders

**Comment by minhDaiVatek** [comment]
+1

**Comment by viva1005** [comment]
This problem was solved (M1, xCode 15.3)
The solution is to remove the double quotes in the library path.

I followed the path below.

https://stackoverflow.com/questions/64098782/react-native-error-ld-library-not-found-for-lbvlineargradient

Type Library Search Paths and search.
Click twice on the path which is beside Library Search Paths and delete the first and the last quote characters.([enter image description here](https://i.stack.imgur.com/LMYWL.png) It should look like this.)

good luck!

**Comment by rakakeak** [comment]
> I solved this problem.(M1, xCode 15.3) The solution is to remove the double quotes in the library path.
> 
> I followed the path below.
> 
> https://stackoverflow.com/questions/64098782/react-native-error-ld-library-not-found-for-lbvlineargradient
> 
> **Type Library Search Paths and search. Click twice on the path which is beside Library Search Paths and delete the first and the last quote characters.([enter image description here](https://i.stack.imgur.com/LMYWL.png) It should look like this.)**
> 
> good luck!

can u update the image? your link can't open. i still have issue for lineargradient

**Comment by vishal-nayak07** [comment]
Facing same issue, i have M1 2020

Library 'BVLinearGradient' not found
Linker command failed with exit code 1 (use -v to see invocation)


"react-native-linear-gradient": "^2.6.2"
"react-native": "0.73.6"

Tried below solution but didn't worked

1. Added below line to podfile
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

2. Added BVLinearGradient in Link binary with libraries under the Build phase

**Comment by umutturkeri** [comment]
any solution? i have same issue

**Comment by AlexAlexandre** [comment]
> I solved this problem.(M1, xCode 15.3) The solution is to remove the double quotes in the library path.
> 
> I followed the path below.
> 
> https://stackoverflow.com/questions/64098782/react-native-error-ld-library-not-found-for-lbvlineargradient
> 
> **Type Library Search Paths and search. Click twice on the path which is beside Library Search Paths and delete the first and the last quote characters.([enter image description here](https://i.stack.imgur.com/LMYWL.png) It should look like this.)**
> 
> good luck!

I just faced this issue, and could be able to fix with this.

**Comment by h1nson** [comment]
Try open the project by .xcworkspace, do not open the project by .xcodeproj. help that works.
